### ISSUE TITLE
Write-up for project proposal (Wiki)

### ISSUE THREAD

**Issue by hlac** [keshok/BaeWatch#1]
Clearly outline what features are already completed from older project and what new features will be implemented this semester.

**Comment by keshok** [comment]
**Existing Features:**
- User(s) can create account
- User(s) can deactivate account
- User(s) can edit profile
- User(s) can select category
- User(s) can view other profiles
- User(s) can search for profiles
- User(s) can comment on other profiles
- User(s) can wink at another/other user(s)
- User(s) can check/view notifications
- User(s) can delete comments
- User(s) can add people to their friends list

**Uncompleted Features:**
- User(s) can block another/other user(s)
- User(s) can send an instant message

**New Features:**
- User(s) can search nearby user(s)
- Implement _uncompleted features_

**Comment by hlac** [comment]
The search for nearby users would use a map for display?

**Comment by keshok** [comment]
**Yes**. It will use the built-in GPS location tracker on the user's smartphone device.

**Comment by hlac** [comment]
Is this done?  What's happening?
