### ISSUE TITLE
As a User, I can select a category

### ISSUE THREAD

**Issue by TorontoJedi** [keshok/BaeWatch#10]

**Comment by keshok** [comment]
#6

**Comment by cessien66** [comment]
![screen shot 2017-03-06 at 3 19 38 pm](https://cloud.githubusercontent.com/assets/25123504/23628123/4ded2a60-0281-11e7-933b-7b96dbeba06f.png)

**Comment by cessien66** [comment]
![screen shot 2017-03-06 at 3 27 45 pm](https://cloud.githubusercontent.com/assets/25123504/23628170/8219f764-0281-11e7-94fa-7cc133100957.png)

**Comment by cessien66** [comment]
![screen shot 2017-03-06 at 3 55 27 pm](https://cloud.githubusercontent.com/assets/25123504/23629317/5ca3c510-0285-11e7-864e-a8a02fd47ddb.png)
