### ISSUE TITLE
As a User, I can search for profiles

### ISSUE THREAD

**Issue by TorontoJedi** [keshok/BaeWatch#12]

**Comment by keshok** [comment]
#6

**Comment by TorontoJedi** [comment]
![screen shot 2017-03-06 at 5 16 46 pm](https://cloud.githubusercontent.com/assets/24237689/23632673/bece87c4-0290-11e7-990b-6df0a9e96efe.png)

**Comment by shervinShams** [comment]
![image](https://cloud.githubusercontent.com/assets/16843909/23877368/5ee36978-0818-11e7-860e-b433b760d2b4.png)

**Comment by shervinShams** [comment]
![image](https://cloud.githubusercontent.com/assets/16843909/23877384/7bd202ec-0818-11e7-9010-f88e9dfedabe.png)

**Comment by shervinShams** [comment]
![image](https://cloud.githubusercontent.com/assets/16843909/23877409/9169439a-0818-11e7-852e-ee8b4997fc07.png)

**Comment by keshok** [comment]
@shervinShams UI looks fine. Please upload the code on GitHub 👍
