### ISSUE TITLE
As a User, I can comment on profiles

### ISSUE THREAD

**Issue by TorontoJedi** [keshok/BaeWatch#13]

**Comment by keshok** [comment]
#6

**Comment by shervinShams** [comment]
![capture](https://cloud.githubusercontent.com/assets/16843909/23525761/804bdf78-ff5d-11e6-8ece-5d301b43648d.PNG)

**Comment by keshok** [comment]
@shervinShams it needs a little more refining. Polish and redesign it a bit more, and then post another screenshot of the updated UI. After doing so, commit changes from the code/solution from Microsoft Visual Studio and the sync it to GitHub. Thanks :)

**Comment by shervinShams** [comment]
![image](https://cloud.githubusercontent.com/assets/16843909/23727149/e1020056-0424-11e7-86d1-e6387c7475d5.png)

**Comment by keshok** [comment]
@shervinShams yeah this looks much better 👍 Now commit and close the issue via GitHub Desktop.
