### ISSUE TITLE
As a User, I can add User(s) to my friends list

### ISSUE THREAD

**Issue by TorontoJedi** [keshok/BaeWatch#19]

**Comment by keshok** [comment]
#6

**Comment by keshok** [comment]
@cessien66 Design a friends list page displaying the user(s) you added.

**Comment by cessien66** [comment]
![image](https://cloud.githubusercontent.com/assets/25123504/23382084/ea7d32a8-fd0e-11e6-8d50-9d9f53af8de0.png)

**Comment by mgill62** [comment]
![capture2](https://cloud.githubusercontent.com/assets/23263177/23632366/a07fd878-028f-11e7-8493-ab6e7c24fe8f.PNG)

**Comment by keshok** [comment]
@mgill62 Okay commit the code GitHub 👍
