### ISSUE TITLE
Setup and configuration

### ISSUE THREAD

**Issue by hlac** [keshok/BaeWatch#2]
1) Deploy on Android (web only at this time).
2) Try Xamarin development environment.

**Comment by keshok** [comment]
**1. Deploy on Android (web only at this time).**
- Current status: Still testing

**2. Try Xamarin development environment.**
- Current status: Underdevelopment

**Comment by hlac** [comment]
Is this done?  What's happening?

**Comment by keshok** [comment]
@hlac We are able to use Xamarin development environment to deploy app in Android via Microsoft Visual Studio 2015

**Comment by hlac** [comment]
Good.  Are you able to connect to your choice of cloud service?


Regards,
Hao C. Lac, Ph.D. (Computational Science)

On Mon, Feb 13, 2017 at 1:25 AM, Keshok Sivalingam <notifications@github.com
