### ISSUE TITLE
As a User, I can log in to my account

### ISSUE THREAD

**Issue by keshok** [keshok/BaeWatch#22]

**Comment by keshok** [comment]
#6

**Comment by TorontoJedi** [comment]
![screen shot 2017-03-19 at 6 09 38 pm](https://cloud.githubusercontent.com/assets/24237689/24085320/316e9adc-0cd0-11e7-96c8-a21387e1b63f.png)

**Comment by keshok** [comment]
@TorontoJedi looks good. Please commit the changes after you insert the code into Xamarin via Microsoft Visual Studio 👍

**Comment by TorontoJedi** [comment]
Ok will do.
