### ISSUE TITLE
Back-end deployment

### ISSUE THREAD

**Issue by hlac** [keshok/BaeWatch#3]
1) Determine cloud service to host database.
2) What type of database (sql or nosql).

**Comment by TorontoJedi** [comment]
**1. Determine cloud service to host database.**
We will be hosting the database using Microsoft Azure

**2. What type of database (sql or nosql).**
Microsoft uses its SQL Server technology to provide a relational database, allowing customers to either access a SQL database on its cloud, or hosted SQL server instances on virtual machines.

**Comment by hlac** [comment]
Is this done?  What's happening?
