### ISSUE TITLE
New features for this version

### ISSUE THREAD

**Issue by hlac** [keshok/BaeWatch#4]
1) Low-fidelity prototype.
2) User stories and associated task.

**Comment by cessien66** [comment]
**1) Low-fidelity prototype.**
![low-fidelity-prototype](https://cloud.githubusercontent.com/assets/10644184/22443030/6581da86-e70b-11e6-9db4-90858b62238a.PNG)

**2) User stories and associated task.**
Project features version#2
Documentation Type - User Stories.
User Stories:

- User can search for nearby users.
- User can contact friends via instant messaging.
- User can access or view previous block list.

_Previous UML Diagram showing features:_
![screen shot 2017-01-29 at 7 33 07 pm](https://cloud.githubusercontent.com/assets/25123504/22409580/ddd256a8-e659-11e6-8332-bcdb1cf5fcb2.png)

_New Features:_
![screen shot 2017-01-29 at 7 48 25 pm](https://cloud.githubusercontent.com/assets/25123504/22409680/f432758e-e65b-11e6-9ff8-1eecf2ad2d79.png)

**Comment by keshok** [comment]
@cessien66 Added low-fidelity prototype diagram

**Comment by hlac** [comment]
Is this done?  What's happening?
