### ISSUE TITLE
As a User, I can create an account 

### ISSUE THREAD

**Issue by TorontoJedi** [keshok/BaeWatch#7]

**Comment by keshok** [comment]
#6

**Comment by mgill62** [comment]
![capture](https://cloud.githubusercontent.com/assets/23263177/23095707/758908b6-f5dc-11e6-84cc-22a33a1f7c3e.PNG)

**Comment by keshok** [comment]
@mgill62 it looks good. You can close the issue now via MS Visual Studio by committing "close #7" under summary/description 👍
