### ISSUE TITLE
As a User, I can deactivate an account

### ISSUE THREAD

**Issue by TorontoJedi** [keshok/BaeWatch#8]

**Comment by keshok** [comment]
#6

**Comment by sarav07** [comment]
![delete_profile](https://cloud.githubusercontent.com/assets/15035860/23630447/1fb8ab62-0289-11e7-9580-7415fb903e19.JPG)

User story is ready to close.

**Comment by keshok** [comment]
@sarav07 Looks good. Commit the code and changes as soon you're finished 👍
