### ISSUE TITLE
As a User, I can edit a profile

### ISSUE THREAD

**Issue by TorontoJedi** [keshok/BaeWatch#9]

**Comment by keshok** [comment]
#6

**Comment by sarav07** [comment]
![edit_profile](https://cloud.githubusercontent.com/assets/15035860/23097136/99e14020-f5fa-11e6-9206-7f0e95195991.JPG)

**Comment by keshok** [comment]
@sarav07 it looks good. Just commit your code and close the issue on Microsoft Visual Studio 👍
